version: "2"
services:
  node:
    build:
      context: web
    volumes:
      - ./web:/usr/src
    ports:
      - 3000:3000
    command: "npm start"
  nginx:
    build:
      context: nginx
    ports:
      - 80:80


